# Generated by Django 5.2.3 on 2025-07-02 11:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('employeereview', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FacultyMonthlyActivities',
            new_name='FacultyMonthlyActivity',
        ),
        migrations.RenameModel(
            old_name='FacultyMonthlyMetrics',
            new_name='FacultyMonthlyMetric',
        ),
        migrations.RenameModel(
            old_name='MilestoneActivities',
            new_name='MilestoneActivity',
        ),
    ]
