# Generated by Django 5.2.4 on 2025-07-10 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeereview', '0002_remove_coursemilestoneactivity_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchactivity',
            name='course_milestone_activity',
        ),
    ]
