# Generated by Django 5.2.4 on 2025-07-05 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('employeereview', '0002_rename_facultymonthlyactivities_facultymonthlyactivity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultymonthlyactivity',
            name='activity',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='facultymonthlyactivity',
            name='day',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='facultymonthlyactivity',
            name='participation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='facultymonthlyactivity',
            name='planned_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facultymonthlyactivity',
            name='remarks',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='facultymonthlyactivity',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Completed', 'Completed')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
        migrations.AlterField(
            model_name='milestoneactivity',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
    ]
