# Generated by Django 5.2.4 on 2025-08-26 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeereview', '0003_remove_batchactivity_course_milestone_activity'),
        ('settings_app', '0006_studentprofile_admission_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesMonthlyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('review_date', models.DateField(help_text='Month & Year of review')),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings_app.salesprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesMonthlyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_value', models.CharField(max_length=100)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeereview.metric')),
                ('monthly_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeereview.salesmonthlyreview')),
            ],
        ),
    ]
