# Generated by Django 5.2.4 on 2025-08-27 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeereview', '0004_salesmonthlyreview_salesmonthlymetric'),
        ('settings_app', '0006_studentprofile_admission_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerMonthlyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_students', models.IntegerField()),
                ('review_date', models.DateField(help_text='Month & Year of review')),
                ('remarks', models.CharField(blank=True, max_length=600, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings_app.batch')),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings_app.facultyprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrainerMonthlyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_value', models.CharField(max_length=100)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeereview.metric')),
                ('monthly_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeereview.trainermonthlyreview')),
            ],
        ),
        migrations.CreateModel(
            name='TrainerMonthlyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings_app.studentprofile')),
                ('monthly_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeereview.trainermonthlyreview')),
            ],
        ),
    ]
