# Generated by Django 5.2.4 on 2025-08-27 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeereview', '0005_trainermonthlyreview_trainermonthlymetric_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainermonthlyactivity',
            name='activity',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='employeereview.batchactivity'),
            preserve_default=False,
        ),
    ]
