# Generated by Django 5.2.4 on 2025-09-08 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeereview', '0006_trainermonthlyactivity_activity'),
        ('settings_app', '0010_studentprofile_placement_pool_added_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salesmonthlyreview',
            name='remarks',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.CreateModel(
            name='PlacementMonthlyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('review_date', models.DateField(help_text='Month & Year of review')),
                ('remarks', models.CharField(blank=True, max_length=600, null=True)),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings_app.placementprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlacementMonthlyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_value', models.CharField(max_length=100)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeereview.metric')),
                ('monthly_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeereview.placementmonthlyreview')),
            ],
        ),
    ]
