# Generated by Django 5.2.4 on 2025-09-22 07:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeereview', '0007_salesmonthlyreview_remarks_placementmonthlyreview_and_more'),
        ('settings_app', '0010_studentprofile_placement_pool_added_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('target_date', models.DateField(help_text='Select month & year for target')),
                ('target_value', models.PositiveIntegerField(help_text='Enter monthly target (e.g. 100 leads, deals, etc.)', validators=[django.core.validators.MinValueValidator(1)])),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sales_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_targets', to='settings_app.salesprofile')),
            ],
            options={
                'ordering': ['-target_date'],
                'unique_together': {('sales_person', 'target_date')},
            },
        ),
    ]
