# Generated by Django 5.2.4 on 2025-08-13 07:08

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0002_facultyprofile_mobile_no_facultyprofile_whatsapp_no'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('isactive', models.BooleanField(default=True, verbose_name='Active')),
                ('mobile_no', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='IN')),
                ('whatsapp_no', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='IN')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings_app.branch')),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reporting_officers', models.ManyToManyField(blank=True, help_text='Select reporting officers (Sales or Managers only)', related_name='sales_reporting_officers', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sales_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-isactive'],
                'abstract': False,
            },
        ),
    ]
