# Generated by Django 5.2.4 on 2025-08-14 06:06

import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0003_salesprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'ordering': ['-isactive']},
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='course',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='student_id',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='created_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='isactive',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='mobile_no',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='IN', unique=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='sales_person',
            field=models.ForeignKey(default=1, help_text='Select the counselor who enrolled this student', on_delete=django.db.models.deletion.CASCADE, related_name='students', to='settings_app.salesprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='whatsapp_no',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='IN', unique=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
