# Generated by Django 5.2.4 on 2025-08-14 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0004_alter_studentprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='drop_out',
            field=models.BooleanField(default=False, verbose_name='Drop Out'),
        ),
    ]
