# Generated by Django 5.2.4 on 2025-08-26 07:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0005_studentprofile_drop_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='admission_date',
            field=models.DateField(default=datetime.datetime(2025, 8, 26, 7, 30, 47, 715562, tzinfo=datetime.timezone.utc), help_text='Month & Year of admission'),
            preserve_default=False,
        ),
    ]
