# Generated by Django 5.2.4 on 2025-09-02 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0006_studentprofile_admission_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='batch_change',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Batch Changed'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='batch_change_date',
            field=models.DateField(blank=True, help_text='Month & Year of Batch Change', null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='dropout_date',
            field=models.DateField(blank=True, help_text='Month & Year of Drop Out', null=True),
        ),
    ]
