# Generated by Django 5.2.4 on 2025-09-02 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0007_studentprofile_batch_change_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='placed',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Placed'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='placed_date',
            field=models.DateField(blank=True, help_text='Month & Year of Placement', null=True),
        ),
    ]
