# Generated by Django 5.2.4 on 2025-09-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0008_studentprofile_placed_studentprofile_placed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='placement_pool_added',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Placement Pool Added'),
        ),
    ]
