# Generated by Django 5.2.4 on 2025-09-08 06:28

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0009_studentprofile_placement_pool_added'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='placement_pool_added_date',
            field=models.DateField(blank=True, help_text='Placement Pool Added Date', null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='batch_change_date',
            field=models.DateField(blank=True, help_text='Batch Changed Date', null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='dropout_date',
            field=models.DateField(blank=True, help_text='Dropped Out Date', null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='placed_date',
            field=models.DateField(blank=True, help_text='Placed Date', null=True),
        ),
        migrations.CreateModel(
            name='PlacementProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('isactive', models.BooleanField(default=True, verbose_name='Active')),
                ('mobile_no', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='IN')),
                ('whatsapp_no', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='IN')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings_app.branch')),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='placement_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-isactive'],
                'abstract': False,
            },
        ),
    ]
